### ISSUE TITLE
Configuration for ASP.NET Core 2.2

### ISSUE THREAD

**Issue by davidkeaveny** [ipjohnson/Grace.DependencyInjection.Extensions#15]
HI there,

I see in the documentation and in the code that the `.UseGrace()` helper method is for .NET Core 3 - do you have an example of how to correctly configure Grace for .NET Core 2.x? (specifically, I'm trying ASP.NET Core 2.2).

Thanks,
David

**Comment by GabrielBBF** [comment]
Definitely don't think it's for 3.0 only, it is used to setup the Grace DI pipeline in 2.x as well.
Here's an example (in your `Program.cs`):

```
new WebHostBuilder().UseGrace()
                    .UseIIS()
                    .UseContentRoot(AppContext.BaseDirectory)
                    .UseStartup<Startup>()
                    .Build()
                    .Run();
```

**Comment by ipjohnson** [comment]
Hi @davidkeaveny 

@GabrielBBF is correct UseGrace is for both 2.X and 3.X applications. Can you make sure you're on version 7.0.1 of the extension library.

**Comment by silkfire** [comment]
The only difference would be that in 3.0, you need to use `IHostBuilder` instead of the soon to be deprecated `WebHostBuilder` (`IWebHostBuilder` will still remain).

**Comment by davidkeaveny** [comment]
Is there any significance in the order in which Grace is registered? In other words, will

```
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
{
    return WebHost.CreateDefaultBuilder(args)
        .UseGrace()
        .UseStartup<Startup>();
}
```

produce the same results as

```
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
{
    return WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .UseGrace();
}
```

**Comment by davidkeaveny** [comment]
Also, is there anything in particular that I need to do to register `ILogger` and/or `ILoggerFactory` from `Microsoft.Extensions.Logging` with Grace? (this is using Grace 7.0.0, Grace.Extensions 7.0.1, and Serilog 2.8.0).

**Comment by ipjohnson** [comment]
@davidkeaveny I don't think it should matter which order. There isn't anything specific you need to do with logging that I'm aware.

What's the specific issue you're running into?

**Comment by davidkeaveny** [comment]
Grace wasn't resolving `ILogger` dependencies e.g.

```
public class LoggingCommandHandlerDecorator<TCommand> : CommandHandler<TCommand>
    where TCommand : ICommand
{
   public LoggingCommandHandlerDecorator<TCommand>(ILogger logger, CommandHandler<TCommand> innerHandler)
   {
   }
}
```

was failing with a `LocateException` on the `ILogger` dependency; however, by using the generic `ILogger<T>` interface, then Grace works as expected, at the expense of quite a lot of visual noise:

```
public class LoggingCommandHandlerDecorator<TCommand> : CommandHandler<TCommand>
    where TCommand : ICommand
{
   public LoggingCommandHandlerDecorator<TCommand>(ILogger<LoggingCommandHandlerDecorator<TCommand>> logger, CommandHandler<TCommand> innerHandler)
   {
   }
}
```

And Resharper constantly nags me to use the `ILogger` interface :-(

I'm assuming that this is more a limitation of the `Microsoft.Extensions.Logging` libraries, is there any way that Grace can work around it?

**Comment by silkfire** [comment]
This is not Grace's fault. The documentation specifies that the only logger that can be resolved is the generic one. The non-generic one is internal, although the generic can be cast to the latter.

**Comment by davidkeaveny** [comment]
I didn't think it was Grace's problem, I was just hoping Grace could help make it happen. If the logging framework is insisting on the generic interface then I guess that's what we're stuck with. Thanks for your help, everything is now working smoothly as far as DI is concerned.

**Comment by ipjohnson** [comment]
@davidkeaveny you could possible rig something up but it would really just be window dressing on top of `ILogger<T>`
