### ISSUE TITLE
using WebApplicationBuilder instead of IHostBuilder

### ISSUE THREAD

**Issue by talfirevic** [ipjohnson/Grace.DependencyInjection.Extensions#31]
If you create a brand new AspNetCore API app, you'll see that it no longer uses `IHostBuilder` but `WebApplicationBuilder `

is there a way to use Grace as DI container in the new aspnetcore API .net 6 apps?

**Comment by silkfire** [comment]
Can't you simply use the `Host` property on the `WebApplicationBuilder`, which implements `IHostBuilder`?

`WebApplicationBuilder.Host.UseGrace()`

**Comment by ipjohnson** [comment]
@silkfire is correct you can do something like this for configuration in the new style startup

```
var builder = WebApplication.CreateBuilder(args);

builder.Host.UseGrace();

builder.Host.ConfigureContainer<IInjectionScope>(scope =>
{
    // custom registration
});
```
