### ISSUE TITLE
Throwing TypeInisializationException when using dotnet core 2.0 on aspnetcore-build:2.0.5-2.1.4 docker image

### ISSUE THREAD

**Issue by aburgett87** [ipjohnson/Grace.DependencyInjection.Extensions#5]
Hi,

When attempting to use Grace in a aspnet core 2.0 application in the aspnetcore-build:2.0.5-2.1.4 docker image the following exception is thrown,

> System.TypeInitializationException: The type initializer for 'Microsoft.Win32.Registry' threw an exception. ---> System.PlatformNotSupportedException: Registry is not supported on this platform.

The Program.cs and Startup.cs code are as follows,

### Program
``` csharp
public class Program
{
    public static void Main(string[] args)
    {
        BuildWebHost(args).Run();
    }

    public static IWebHost BuildWebHost(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseGrace()
            .UseStartup<Startup>()
            .Build();
}
```
### Startup
``` csharp
...
public void ConfigureContainer(IInjectionScope scope)
{
}
...
```

**Comment by ipjohnson** [comment]
Hi @aburgett87 

I believe your problem is the same as this one [here](https://github.com/ipjohnson/Grace/issues/111). The technical details as well as the fix are included in the issue. 

Give it a whirl and let me know how it works out.

**Comment by ipjohnson** [comment]
I'm going to close this
